SPACE = '.'
ROBOT = 'R'
OBSTA = 'X'


tablero = (
    [SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE],
    [SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE],
    [SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE],
    [SPACE, SPACE, SPACE, ROBOT, SPACE, SPACE, SPACE],
    [SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE],
    [SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE],
    [SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE],
    [SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE],
)
